server:
  port: 9078

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping
    driver-class-name: org.postgresql.Driver
    username: admin
    password: yourpassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        default_schema: public
